quarkus:
  application:
    name: q-auth-service

app:
  external-oauth2:
#    git-hub:
#      client-id: github-clientId
#      client-secret: github-clientSecret
#    google:
#      client-id: <google-client-id>
#      client-secret: <google-client-secret>
#    facebook:
#      client-id: <facebook-client-id>
#      client-secret: <facebook-client-secret>
